### ISSUE TITLE
Problem and questions

### ISSUE THREAD

**Issue by happysurf** [schomery/popup-blocker#1]
First of all compliments for this great tool, the best in my opinion on his category.
There is some problems and questions:
- The popup-blocker conflict with the built-in Firefox blocker, if this is disabled your tool works fine, please clarify this.
Example: On this page http://www.freshremix.ru/chillout/101546-best-of-chillout-2015.html if you click on UPLOADED, TURBOBIT or HITFLE buttons the popup link is displayed, then click on Allow but then the new tab is blocked by Firefox, if the built-in blocker is disabled then the new tab is correctly opened. 
- Same problem on this page http://www.italia-film.co/star-trek-the-original-series-1966-1969-streaming/ but in addition there is also a glitch like this:

![84f153605ba54e4a9a6645f73d8ac534](https://cloud.githubusercontent.com/assets/13637587/20038805/fc8786d4-a439-11e6-832d-7b397d64e7ea.png)

All with Firefox 50 on two PC (Windows XP and 7).
Thanks.

**Comment by schomery** [comment]
> The popup-blocker conflict with the built-in Firefox blocker

Thanks for the report. I added a new button to the UI. It is now possible to open popup requests in  background tabs as well. Basically if you allow popup from the UI, the extension only resumes normal popup request. So there is always a chance that the built-in popup blocker catches this request. However, for "redirect" and "Background" extension handles the opening requests. To prevent conflict with the internal blocker, use "redirect" or "background" options.

> but in addition there is also a glitch like this:

Should have been resolved in 0.1.6. Please reopen if not.

**Comment by happysurf** [comment]
All is OK now, except for some link recognized as false positive.
Go to http://www.ghacks.net/2016/11/07/nvidia-telemetry-tracking/ and then click on Home button.

**Comment by schomery** [comment]
So all the links that try to be opened in a new tab/window are blocked for user attention regardless of their origin. This is intentional.

**Comment by happysurf** [comment]
OK, you are right.
Thanks.

**Comment by happysurf** [comment]
Sorry, I have discovered an other graphic problem:
Go to https://www.youtube.com/watch?v=I01m7eSGU9c&feature=youtu.be and then click on the link below the video http://www.reverbnation.com/lewisluong/song/17482778-perto-de-voc-close-to-you
The popup windows is back to YouTube bar.

![overlapping](https://cloud.githubusercontent.com/assets/13637587/20091348/9effe70e-a592-11e6-8cae-2afd0b6780a1.jpg)

**Comment by schomery** [comment]
Nice catch!

Can you confirm the fix on the latest dev version?

Download https://github.com/schomery/popup-blocker/archive/master.zip, extract it on a folder. Now open about:debugging and point the browse button to the "manifest.json" file inside the extracted folder. Then refresh the page.

**Comment by happysurf** [comment]
Now the popup windows is correctly opened above the page but if you click on _deny_ there is a delay before closing.

**Comment by schomery** [comment]
Delay is because of async communication. Is this noticeable on other websites too?

**Comment by happysurf** [comment]
Yes, same delay for any pages.

**Comment by schomery** [comment]
I made some changes to have faster user actions; https://github.com/schomery/popup-blocker/archive/master.zip

Please give this version a try.

**Comment by happysurf** [comment]
Same problem, in addition if I click on **allow** button is open a blank page instead the source link.

**Comment by schomery** [comment]
Please uninstall the extension from about:addons then do a restart and install the latest dev version from about:debugging and see if it helps or not.

**Comment by happysurf** [comment]
Now the popup closing delay is fixed but when I click on **allow**button is opened a blank page, then after 2 or 3 seconds is loaded the correct link.

**Comment by schomery** [comment]
I'll see if I can improve the opening performance. Thanks for the report.
