### ISSUE TITLE
Add Russian.

### ISSUE THREAD

**Issue by wvxwxvw** [schomery/popup-blocker#100]
See the Pull requests

**Comment by smed79** [comment]
#99

**Comment by wvxwxvw** [comment]
Reinterpreted the translation.

Fork with full Russian translation and some other changes. I did it more for myself.
https://github.com/wvxwxvw/webextensions/tree/master/Popup_blocker_(strict)

**Comment by schomery** [comment]
Please submit to https://www.transifex.com/github-7/popup-blocker-strict
