### ISSUE TITLE
Add a list of domains to redirect

### ISSUE THREAD

**Issue by wvxwxvw** [schomery/popup-blocker#102]
Add a white list of domains to redirect, to block empty pages created when downloading from file sharing sites and other sources of downloaded files.

It is somehow illogical, there are white lists of sources and targets, but there is no list for redirects. But this is one of the most important functions because of which users can choose this add-on.

This wonderful addon wants to get a white list for redirects. )

**Comment by schomery** [comment]
I am not sure if it is doable. The redirect blocking means that the extension asks your browser to prevent any page redirection for about 2 seconds after a popup is caught. The message is shown by the browser when a redirect is requested within this time frame. There is no info about what the destination address would be, so at current implementation, there is no way to have white/black-lists.
