### ISSUE TITLE
popup not blocking

### ISSUE THREAD

**Issue by Shironep** [schomery/popup-blocker#105]
Good night, so, recently this website the popup is not blocking the popup from appearing > https://animeshouse.net/ opening the website and trying to click in anything u will see.

chrome extension from the store, also.

hope is there a fix for this :D

**Comment by narcolepticinsomniac** [comment]
Not sure if the site is geo-blocking, or what, but I get "500 Internal Server Error" trying to follow that link from the US.

**Comment by Shironep** [comment]
ah yes, sorry, forgot to mention, but this website for some reason is allowed only here in (brazil), if u can use a vpn or something like that to access.

**Comment by narcolepticinsomniac** [comment]
>use a vpn 

Nah. I'm not the dev, so it doesn't really matter, but I doubt he'll wanna either. I was just curious, because I haven't seen a popup slip by in a while, and I frequent some pretty sketchy sites.

>chrome extension from the store, also.

Are you saying you're using a special extension for the site? If so, the extension may be the cause of these popups. Extensions have a built-in API to open tabs, which no popup blocker could prevent.

**Comment by Shironep** [comment]
no, i mean the extension published in the store (chrome) > https://chrome.google.com/webstore/detail/popup-blocker-strict/aefkmifgmaafnojlojpnekbpbmjiiogg - and this started to happen recently, never saw this happening in this website, also when i tried the site that test this extension, redirects from others pages was allowing

**Comment by narcolepticinsomniac** [comment]
>also when i tried the site that test this extension, redirects from others pages was allowing

@schomery PBS does seem to be failing some of its own tests. I see popups allowed by 6, 12.1, 12.3,  and 12.4 in either browser. Also 17.1 and 17.2 in FF.

**Comment by schomery** [comment]
@Shironep do you have another sample without IP restriction?

**Comment by Shironep** [comment]
> @Shironep do you have another sample without IP restriction?

nop

**Comment by schomery** [comment]
@narcolepticinsomniac 6, 12.1, 12.3, and 12.4 tests do not issue popup anymore, so the redirection is allowed. I'll add some notes to the page. 17.2 gets blocked for me in FF. 17.1 needs to be investigated.

**Comment by schomery** [comment]
@Shironep we are now protecting against a new method (see tests  #13.1 and #13.2 of https://webbrowsertools.com/popup-blocker/) on version 0.5.3 release. So hopefully, it will cover your case too. If not, please reopen
