### ISSUE TITLE
Blocks valid iframe use in Roundcube webmail

### ISSUE THREAD

**Issue by alecpl** [schomery/popup-blocker#106]
Roundcube (a widely used app) uses hidden iframes for sending email and saving a draft. Interestingly it does not block other uses of iframe, e.g. for file uploads.

Is there any way to detect that an iframe has been blocked? Or maybe it is a bug in the plugin that should be fixed? Any help would be appreciated.

Reference: https://github.com/roundcube/roundcubemail/issues/7427

**Comment by schomery** [comment]
Is there an easy way to test "Roundcube" without installing it on a server?

**Comment by alecpl** [comment]
@schomery I can provide you a kolabnow.com account for tests. Please, write an email to alec at alec.pl.

**Comment by schomery** [comment]
Thanks! It should be fixed by the next release.

**Comment by alecpl** [comment]
Great. The problem was with saving draft/sending an email, but also contact photo upload? Did you tested both?

**Comment by schomery** [comment]
Both seems to be fixed. You can try it yourself too. First disable the production version of PPB and load the developer version from about:debugging and see if it works or not.

https://github.com/schomery/popup-blocker/archive/master.zip
