### ISSUE TITLE
A popup is slipping

### ISSUE THREAD

**Issue by thevalo** [schomery/popup-blocker#107]
Hello, I found that his page https://www.webroot.com/services/popuptester1.htm is able to open a popup, though it is about:blank (either intentionally or not). Why that would happen? Is it just me?

**Comment by schomery** [comment]
Even on 0.5.2 release? What is your browser?

**Comment by thevalo** [comment]
No, it seems like when writing this issue I must've had older version than 0.5.2.
Problem fixed.
