### ISSUE TITLE
Request: Set default action for countdown.

### ISSUE THREAD

**Issue by htomeload** [schomery/popup-blocker#11]
I just saw new feature countdown before perform action. It nice feature but I think it will be better than now if it can do set default action for all sites when counting down to zero (Deny, Allow, Redirect, Background). It will help many user to not perform first action to all popup sites.

**Comment by schomery** [comment]
We will have this option on the next release. Thanks for the suggestion. For now you can give the dev version a try; instruction: https://github.com/schomery/popup-blocker/issues/8#issuecomment-271232524
