### ISSUE TITLE
Possible malware? Using Popup blocker causes "Download" button to appear under YouTube videos.

### ISSUE THREAD

**Issue by EbisuGit** [schomery/popup-blocker#113]
Not sure if it's this software that causes that or is used as middle man, but it's definitely related.

Reddit thread:
https://www.reddit.com/r/youtube/comments/ilb6th/my_friend_has_this_download_button_pop_up_which/

Direct image of the problem:
https://i.redd.it/3at27ap6rrk51.jpg

Please look into it.

**Comment by narcolepticinsomniac** [comment]
>it's definitely related

You should try to avoid words like "definitely", when you don't know what you're talking about. The extension being discussed in that reddit thread is a completely different popup blocker extension.

**Comment by schomery** [comment]
@EbisuGit, you need to notify the developer of "Popup Blocker Pro" extension I guess. "Popup Blocker (**strict**)" does NOT visually alter any page in any way whatsoever.
