### ISSUE TITLE
Whitelisting with "trust" button not adding hostname to Whitelist Sources

### ISSUE THREAD

**Issue by brellaumpixel** [schomery/popup-blocker#114]
Whitelisting any source hostname via "trust" button not working.
i.e. When clicking "**trust**" button the source hostname not being added to **whitelist sources**

in addon Options have  "When 'trust' button is pressed, add hostname to" = `Whitelist Sources`

- Whitelisting a destination works with no problems
- Whitelisting a source worked in Version 0.5.1.3 so have currently rolled back to this version
- Tested all Versions 0.5.2-0.5.6 and problem exists in all

Using FF v80 on 64bit Win7

**Comment by brellaumpixel** [comment]
UPDATE:
Have done some debug testing and found adding "tabs" to `permissions` section of manifest.json fixes problem.

Don't know how to implement that on an 'live' (not the addon debugging) version

**Comment by schomery** [comment]
Thanks for the report. Will get fixed by the next release
