### ISSUE TITLE
Please change the icon to make it easier to determine if the strict popup blocker is enabled or disabled

### ISSUE THREAD

**Issue by mathit1** [schomery/popup-blocker#115]
On FHD displays, it is nearly impossible to know if the popup blocker is enabled (on) or disabled (off).  Can you change the add-on icon to make it more obvious (maybe add "green" to the icon for "enabled" and "red" for "disabled"?

Thanks for considering.

**Comment by wyxchari** [comment]
Yes, I confirm the above message. The colors of the Popup Blocker icon are very similar and you cannot tell if it is enabled or disabled. In addition, it is not understood how it works since sometimes it seems that half an icon turns one color and the other half another and I don't know what it means.

**Comment by schomery** [comment]
Thanks for the report. I added a new FAQ to the home page to explain the meanings. Also, we are using two new colors for the enabled and disabled states.

https://add0n.com/popup-blocker.html?rev#faq2

**Comment by wyxchari2** [comment]
Thank you very much. Now the colors of the icons are perfect and the 4 states of the icon can be perfectly distinguished. 
Again, thank you very much.

**Comment by mathit1** [comment]
Thank YOU!  It is much easier to understand now. 


———Delete Facebook 

On Tuesday, January 12, 2021, 11:03 AM, wyxchari2 <notifications@github.com> wrote:




Thank you very much. Now the colors of the icons are perfect and the 4 states of the icon can be perfectly distinguished.
Again, thank you very much.
