### ISSUE TITLE
not block popup vermangasporno.com (NSFW)

### ISSUE THREAD

**Issue by wernser412** [schomery/popup-blocker#121]
1. Enter ```https://vermangasporno.com/kono-subarashii-sekai-ni-syukufuku-o/```
2. I get popup when entering to read.

**Comment by wernser412** [comment]
@schomery popup

**Comment by schomery** [comment]
I am not able to reproduce this on Chrome.

make sure to enable "Prevent page redirection for 2 seconds after a popup is requested" on the options page.

What is your browser? how about your OS?

**Comment by wernser412** [comment]
> No puedo reproducir esto en Chrome.
> 
> asegúrese de habilitar "Evitar la redirección de la página durante 2 segundos después de que se solicite una ventana emergente" en la página de opciones.
> 
> ¿Cuál es tu navegador? ¿qué hay de su sistema operativo?

Maybe popup appears to me.

Chrome 89.0.4389.114, SO Windows 7 ultimate
