### ISSUE TITLE
Blocking pop-ups even when disabled. 

### ISSUE THREAD

**Issue by mlgmaster666** [schomery/popup-blocker#123]
I'm having this issue where the popup blocker keeps blocking useful popups even after i disable it.
This doesn't happened if I disable the extension entirely in the browser settings.
The most recent occurrence was in the GOG checkout with PayPal. 

Edgium v88.0.705.50, popup blocker v0.5.9.

**Comment by Hertzila** [comment]
I'm having the same issue. The blocker keeps blocking popups despite adding the domain into the whitelists, and globally disabling the blocker. The only way to allow the popup I want to allow is to completely disable the extension from the add-on settings.
Happened with Final Fantasy XIV's checkout system.

Firefox 86.0.1 64-bit, Popup Blocker v0.5.9.

**Comment by wyxchari** [comment]
Another page not working:
https://translatesubtitles.com/subtitletranslator/index.php
A selection box should appear to choose the language in the center of the screen. Even whitelisting it keeps blocking.
