### ISSUE TITLE
not block popup simply-hentai[dot]com (NSFW)

### ISSUE THREAD

**Issue by wernser412** [schomery/popup-blocker#125]
1.- Enter : `https://www.simply-hentai[dot]com/historys-strongest-disciple-kenichi/nippon-jyushidesuwa%E2%98%86-%EC%9D%BC%EB%B3%B8-%EC%A5%AC%EC%8B%9C-%EC%9E%85%EB%8B%88%EB%8B%A4%E2%98%86/page/6590446`

2.- Clicking on the image does not block the popup

**Comment by schomery** [comment]
do you have the "Prevent page redirection for 2 seconds after a popup is requested" option checked?

**Comment by schomery** [comment]
What is your browser?

**Comment by wernser412** [comment]
here a video of the problem

https://vimeo.com/509746071



> do you have the "Prevent page redirection for 2 seconds after a popup is requested" option checked?

Yes



> What is your browser?

Chrome

**Comment by schomery** [comment]
Unless otherwise, you have forgotten to press the save button on the options page, I am still not able to reproduce this.
