### ISSUE TITLE
Breaking reCAPTCHA in some websites

### ISSUE THREAD

**Issue by Knightscover** [schomery/popup-blocker#130]
I'm unable to see, let alone solve reCAPTCHA challenges in some websites with this add-on enabled. I only noticed this recently, so it's probably been happening since a recent update.
Note that this does not affect all websites. I can see and solve it on Google's demo page: https://www.google.com/recaptcha/api2/demo
On the other hand, I can't log into websites such as https://www.overleaf.com/login

Disabling the add-on globally or just for this hostname both fix the issue. It's worth noting that the add-on does not show any notifications about having blocked a request when this happens though, which left me puzzled for a while trying to figure out what was wrong.

**Comment by raennik** [comment]
Confirming report - am having various issues with sites trying to pull up recaptcha boxes (not previously an issue, so unsure if something changed here, or with Google). Generates an "Uncaught DOMException: Permission denied to access property "document" on cross-origin object" in Inspector. 

I've tried whitelisting google.com, gstatic.com, and the site names, both as destinations and sources, but issue presently persists.

**Comment by Abhinav1217** [comment]
I came here for submitting same issue. I get a "Could not connect to reCaptcha service" error since last update few days ago. 
My extension is installed from mozilla addons site. It was working about a week ago, but not anymore. I spent 2 days to narrow it down to this add-on. 

Previously recaptcha's were working fine and ads popups were still blocked. This is happening only since about a week.  

Browser: Mozilla firefox 89
OS: Solus OS (Linux 64bit)

![Screenshot from 2021-06-20 10-08-42](https://user-images.githubusercontent.com/740584/122662323-b28d0380-d1af-11eb-8fdd-0f8cd4784a67.png)

**Comment by tomo90** [comment]
I also confirm the issue. I'm having problem with loading videos on numerous websites that use Google's reCaptcha.

**Comment by Mikaill** [comment]
Also confirming this issue, multiple different websites using Google's reCaptcha won't let me log in / proceed (even if there is no pop-up), stopped occurring after disabling the add-on.

OS: Windows 10 Pro 20H2
Browser: Mozilla Firefox 90.0b10 (64-bit)

**Comment by scribble-de-gook** [comment]
Also confirming issue. Affects both firefox and chromium.

OS: Manjaro Linux (64-bit)
Browser: Firefox 89.0.1; Chromium 91.0.4472.106

**Comment by trespordez** [comment]
Also confirming this issue x3, i've spent about 40 minutes to figure it out.

OS: Windows 7 (x64)
Browser: Firefox 89.0.1 (x64)
Version: 0.6.5

**Comment by zenis0102** [comment]
Same here and like the others confirming the issue. It used to work fine but _after the recent automatic update_ it blocks or prevents **rcapcha** and **hcaptha** from loading.

OS: **Windows 10 x64 Pro**
Browsers: **Google Chrome**, **Mozilla Firefox**, **Edge**, **Opera**, **Slimjet** (all recent versions and both x86 and x64)

**Comment by koobs** [comment]
- PBS Version: 0.6.5
- Affected: epicgames.com login
- Type: hCaptcha

PBS Version 0.6.2 (available via firefox addons site) is **not** affected

**Comment by CrocodileCroco** [comment]
Same issue

OS : Windows 10
Browser : Firefox 89.0.2 (64 bits)
Type : Google reCaptcha
