### ISSUE TITLE
Blocks video play on tubitv.com

### ISSUE THREAD

**Issue by ifucan17** [schomery/popup-blocker#131]
When clicking play, the video does not play unless I disable this extension on that website. Seems kind of odd because there is no popup when playing a video.

**Comment by Miltora** [comment]
Not just tubitv.com, also some videos on crunchyroll are blocking for example. It wasn't always like that, only a few days ago

**Comment by schomery** [comment]
Please reopen if you are still experiencing the issue after updating to the latest release.
