### ISSUE TITLE
reCAPTCHA's stopped working

### ISSUE THREAD

**Issue by dymester** [schomery/popup-blocker#133]
The title says it all, reCAPTCHA's have stopped working on all websites. Happens on both the latest versions of Chrome and Vivaldi.

**Comment by schomery** [comment]
do you have the latest version of the extension? 0.6.6

**Comment by dymester** [comment]
Sorry forgot the data:

Extension Version: 0.6.6
Browser: Vivaldi 4.0.2312.27 (Stable channel) (64-bits)
Revision: 662c525b22ae8cc0ab64eff2356753242f3ebb91
reCAPTCHA's I used for testing: Random websites and https://patrickhlauke.github.io/recaptcha/

Began around one week ago. It seems to be blocking the reCAP window itself, as the button works normally. 
If I disable the plugin, solve puzzle, reload the page(or go to another) and then enable the plugin again, no window shows but reCAP is still cleared.

**Comment by schomery** [comment]
@dymester I can reproduce this with v0.6.5, but not with v0.6.6 release (using the provided page)

**Comment by dymester** [comment]
Based on what you said, I checked if there were any other external factors. It seems to be something related with me using Tampermonkey.

**BOTH** Tamper and PopBlo: No reCAP;
**ONLY** Tamper: reCAP as usual;
**ONLY** PopBlo: reCAP as usual;

I don't really know how they are interacting... I probably have a script running amok... but yeah problem from my side, sorry for that.

**Comment by schomery** [comment]
Having TM installed without any scripts doesn't seem to conflict with PP. If there is any particular script that conflicts, I can take a look.

**Comment by dymester** [comment]
Same, if i disable them all...

Imma look it up after work. Thx anyways.
