### ISSUE TITLE
not block popup

### ISSUE THREAD

**Issue by wernser412** [schomery/popup-blocker#134]
not block popup:
https://prostylex.org/torrents-details.php?id=613328

Popup Blocker (strict) 0.6.6
chrome_installer 91.0.4472.124

**Comment by schomery** [comment]
I am not able to reproduce this. Can you confirm on a clean profile?

**Comment by wernser412** [comment]
detects it but at the same time redirects it directly
![2](https://user-images.githubusercontent.com/53667212/127781899-efdd9b94-9402-42ec-af58-38e93fade0a1.jpg)

![2021-05-26_154108](https://user-images.githubusercontent.com/53667212/127782040-22e97282-de27-4092-93d4-b7faff1921ef.jpg)

I already set in options but I still can't fix it

**Comment by schomery** [comment]
Do you have the prevent redirection enabled on the options page?

**Comment by wernser412** [comment]
Thanks it worked after activating the option and clearing the cache and cookies, this option should be activated as default
