### ISSUE TITLE
Page does not work. Disabling "This Hostname" does not work.

### ISSUE THREAD

**Issue by wyxchari** [schomery/popup-blocker#135]
Another page that does not work with Popup Blocker (strict) 0.6.6: https://ov.aguasdelhuesna.com/solicitud-de-tarifas-especiales
Firefox: The "Añadir Documento" button does not work. Disabling "This Hostname" does not work. Only disabling Popup Blocker "Globally" makes the button work or completely disabled the plugin in the Firefox options. Firefox in private Windows also work.

**Comment by schomery** [comment]
Thanks for the report should be fixed by the new release.
