### ISSUE TITLE
firefox 45.6 esr

### ISSUE THREAD

**Issue by heforfree** [schomery/popup-blocker#14]
hello if you don't mind please add support for Firefox 45.6 esr
i am able to install its normally from addons.mozilla.org
its catch popup show count but don't show that allow deny request of addon

thanks

**Comment by heforfree** [comment]
also in test page following test 1/1 1/2   2/1  2/2  3
does not count in toolbar icon

**Comment by schomery** [comment]
Unfortunetly there is nothing I can do to fix this. Popup Blocker (strict) is based on WebExtension and seems like 45.6 ESR does not fully support WebExtension. WebExtension is very limited in low level API access and hence there is no way to fix anything related to the internal code; in this case badge number.

**Comment by heforfree** [comment]
will i have to wait Firefox become better in newer version then upgrade(after firefox 45 every version go slower).wish you make another compatible popup blocker for older version.i will close Issue but if you have time to create version for older Firefox then reopen it.
thank you
