### ISSUE TITLE
New version Issues

### ISSUE THREAD

**Issue by rayman89** [schomery/popup-blocker#15]
When using the new version the pop ups I get do nothing even if I click allow the pop-up does not show and deny does not add the site to the blacklist also I think there was supposed to be more buttons on this version other than deny and allow I'm only seeing those two.

My settings are 3, 3, 0, do nothing and the only ticked option is the one before the last one. I'm on windows 7 x64 firefox 51

**Comment by schomery** [comment]
If the blocked popup is http or https schemes, there are more buttons. For JavaScript popups where the destination is unknown there are only two buttons.
Here is how it looks on FF 50.1 when HTTP scheme is requested
![screen shot 2017-01-20 at 10 03 46](https://cloud.githubusercontent.com/assets/11704051/22138820/d0f5f8ea-def7-11e6-909a-79e16b0a0278.png)

> When using the new version the pop ups I get do nothing even if I click allow the pop-up does not show

Can you provide a sample page with this issue? Is this working on the test page? http://tools.add0n.com/popup-blocker.html

> deny does not add the site to the blacklist

deny is not supposed to add the site to the blacklist at all. It is supposed to deny popup showing.

**Comment by rayman89** [comment]
On the site you provided to test and other sites like http://www.popuptest.com/ the allow button still doesn't make the pop-up appear I think the default firefox pop up blocker it because I see the firefox pop up blocker icon on the url bar but the thing is that if your add-on is disabled firefox doesn't block it so I don't know what happens. Also on some cases even if I click on the icon to disable the add-on the allow/deny pop-up still appears (this test page is an example http://www.popuptest.com/popuptest12.html ) Also I was under the impression that the add-on now remembers your decisions or something like that. Was it not implemented? If it's how does it work?

**Comment by schomery** [comment]
> Also on some cases even if I click on the icon to disable the add-on the allow/deny pop-up still appears

Well, by default when a page is opened, the popup blocker is enabled. Then if it is actually disabled, a message is sent to the script disabling the observer. For http://www.popuptest.com/popuptest12.html page, it executes the popup even before message passing is complete and hence the popup is blocked. Unfortunetly there is no safe way to prevent this.

> Also I was under the impression that the add-on now remembers your decisions

True, however, there was a bug. So one of the detector functions wasn't resolving the URLs to convert them to absolute path. It will be fixed on the next release. Thanks!

> while your add-on is on if you click allow the default firefox popup blocker blocks the pop up

There is no way to fix this. Instead use open in background or redirect page. When a popup is allowed by extension, Firefox built-in blocker can still find it suspicious and can block the popup for user attention. You can either use the other options (with above fix, they will be available on more popups) or disable the Firefox popup blocker completely which is not recommended.

**Comment by schomery** [comment]
Please reopen if you are still experiencing this issue.
