### ISSUE TITLE
setting not saved

### ISSUE THREAD

**Issue by juanjotoronja** [schomery/popup-blocker#16]
Installed last version 0.2.5 and when i tick on "prevent page redirection..." and save changes, after i leave and come back the option is not ticked.

**Comment by schomery** [comment]
Thanks for the report. What is your browser?

**Comment by juanjotoronja** [comment]
Firefox 49.0.2 on WIN 7 x64

**Comment by schomery** [comment]
This should have been fixed on the latest dev version. You can give it a try right now (https://github.com/schomery/popup-blocker/tree/master/src) or wait for this version to hit the release channel.

**Comment by juanjotoronja** [comment]
OK thanks I'll wait for the official release on mozilla.

**Comment by schomery** [comment]
New version is now available.
