### ISSUE TITLE
window.open is bypassed message

### ISSUE THREAD

**Issue by rayman89** [schomery/popup-blocker#17]
On the test page http://tools.add0n.com/popup-blocker.html
with window.open button pressed method 3, 14 and 16/2 display a message saying that window.open is bypassed and that it should be blocked. 

And with mouse event button pressed methods 2/1, 3, 14 and 16/2 displays the same message. 

Why is it showing and what does it mean?

**Comment by schomery** [comment]
There is a button in the test page to overwrite `window.open` function. You must have clicked it before running the tests. In Firefox, it is possible to overwrite this function and hence you get the alert message which is basically a simple callback to notify you this function is overwritten. Still popup blocker should be effective and prevent the popups.
