### ISSUE TITLE
Disable/activate button broken

### ISSUE THREAD

**Issue by davidhedlund** [schomery/popup-blocker#19]
This [link](http://www.tabussen.nu/ultra/planera-resa/?from=Ume%C3%A5+Assistentv%C3%A4gen|25107|0&to=Ume%C3%A5+Vasaplan|25332|0&date=&departureTime=&departureTime_submit=&searchStations=S%C3%B6k+resa) doesn't work with the add-on.

I clicked on the "Popup Blocker (strict)" button next to the navigation bar to disable it, then I refresh the the URL, still it doesn't work.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by schomery** [comment]
>  still it doesn't work.

Can you be more specific. You mean it still block something in this page? How can I reproduce this

**Comment by davidhedlund** [comment]
@schomery 
> You mean it still block something in this page?

Exactly.

> How can I reproduce this

Visit the link that I provided and compare it with and without Popup Blocker (strict) enabled/disabled.

**Comment by davidhedlund** [comment]
@schomery Just remember that you have to disable the add-on not from the Add-on list but from the add-on button field that is located right to the search bar.

**Comment by davidhedlund** [comment]
![screenshot from 2017-02-10 08 05 50](https://cloud.githubusercontent.com/assets/6416073/22817533/20fd8ba2-ef68-11e6-8644-a68724be080e.png)

**Comment by schomery** [comment]
Thanks for the report. Version 0.2.7 should fix this. Please wait for update and reopen if not

**Comment by davidhedlund** [comment]
[mylabel:re-evaluate](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Are-evaluate%22+in%3Acomments&type=Issues&ref=searchresults)
