### ISSUE TITLE
I cannot install it.

### ISSUE THREAD

**Issue by lagun** [schomery/popup-blocker#2]
i tried many time but can't install it.
cyberfox 50 32bit latest version
win 8.1 64bit
picture.
http://www.bild.me/bild.php?file=7223888Untitled.png

(((Request)))
- whitelist website

**Comment by schomery** [comment]
Can you try the latest dev version?

Download https://github.com/schomery/popup-blocker/archive/master.zip, extract it in a folder. Open about:debugging in a browser tab and point the "Load Temporary add-on" button to the manifest located in the root directory and see if it works or not.

**Comment by lagun** [comment]
i tried it. when i follow your way and it show icon but i close browser and open again icon disappear. 
Watch my video to saw my problem.
https://sendvid.com/q7mwnoiv

**Comment by schomery** [comment]
I just wanted to make sure the extension itself can be installed on your FF. The reason it disappear after restart is you have installed the dev version. 

Try to download the release version from Mozilla website and drop it into your Firefox browser and see if it gets installed or not

**Comment by lagun** [comment]
i download from  Mozilla website but it can't install.
http://www.bild.me/bild.php?file=7223888Untitled.png

**Comment by schomery** [comment]
There must be something wrong with WebExtension installation in "cyberfox". Can you give it a try on a clean profile?

**Comment by schomery** [comment]
http://stackoverflow.com/questions/39854127/add-on-appears-to-be-corrupt-when-trying-to-install-my-add-ons-xpi-file-in-f

This might help: change the extension from xpi to zip. Uncompress the zip somewhere and re-pack it using your Windows built-in zip tool. Rename the extension back to xpi and drop it into your Cyberfox. See if it works or not.

**Comment by idoet** [comment]
Hi, @schomery
can you add this to manifest.json?
`  "applications": {
     "gecko": {
          "id": "something@mozilla.org"
     }
  }`

[source](https://discourse.mozilla-community.org/t/webextensions-this-add-on-could-not-be-installed-because-it-appears-to-be-corrupt/3668/6)
it work for me

**Comment by schomery** [comment]
This will cause
![screen shot 2016-11-20 at 10 54 25](https://cloud.githubusercontent.com/assets/11704051/20461331/c3db195a-af0f-11e6-8b33-7ed1dcf8dd52.png)
 on Chromium (Opera and Google Chrome)

I can do this just before pushing to AMO. Hopefully I am going to remember this!

**Comment by schomery** [comment]
Is this issue fixed with my latest release?

**Comment by idoet** [comment]
Yes, fixed, thanks @schomery

**Comment by schomery** [comment]
Great, thanks for the report.
