### ISSUE TITLE
Badge Number & PTSD

### ISSUE THREAD

**Issue by J-J-L** [schomery/popup-blocker#20]
badge number: Red can be a powerful traumatic-memory trigger for people like me with PTSD (Post Traumatic Stress Disorder) --whats 'triggered' are disabling flashbacks, amnesia episodes & more. The less red in my environment the better. 10% of the population is susceptible to developing PTSD. 
--Please add a simple option to change the color away from red (even to b&w)
--or a simple option to disable the badge number feature. 
--I don't know code, but if you could provide a cut/paste or delete I could apply to the .xpi file via console (mac) then I could, at the very least, take care of it for myself.
Much Thanks in advance ~JL

**Comment by schomery** [comment]
![screen shot 2017-02-07 at 11 42 39](https://cloud.githubusercontent.com/assets/11704051/22682900/acee0cb2-ed2a-11e6-8517-3f52a4a3dbdf.png)

We already have an option to disable the toolbar badge, however there is no color setting. From the next version this new option is also available.

Thanks for the suggestion.

**Comment by schomery** [comment]
btw, the default badge background color is changed to the color shown in the new setting.

**Comment by J-J-L** [comment]
Thank You =D
