### ISSUE TITLE
https://www.baemin.com/ site click event not work

### ISSUE THREAD

**Issue by DandyClubs** [schomery/popup-blocker#21]
firefox 51.0.1 x64

Popup Blocker (strict) 0.2.6 install

i visit https://www.baemin.com/

click event not work.

only firefox not work  but chrome is work.

wildcard * is not support?

www7.cbox.ws
www4.cbox.ws

i add whitelist cbox.ws 
but not work

i add *.cbox.ws 
but not work.

**Comment by schomery** [comment]
So you mean it still displays popups? or the filter to white-list domains is not working?

**Comment by DandyClubs** [comment]
i add cbox.ws (white-list(popup))
 still display popup allow or deny 

http://prntscr.com/e8ho1q

**Comment by schomery** [comment]
Where should I click to get this popup on https://www.baemin.com/

**Comment by DandyClubs** [comment]
http://prntscr.com/e8hp4x

https://www.baemin.com/

i click pizza but change paeg not work

**Comment by schomery** [comment]
If I click on the pizza item, the page redirects to https://www.baemin.com/list/%ED%94%BC%EC%9E%90/%EC%84%9C%EC%9A%B8_%EC%84%9D%EC%B4%8C%EB%8F%99

There is no popup.

**Comment by DandyClubs** [comment]
i make firefox new profile and only install Popup Blocker (strict) 0.2.6

https://www.baemin.com/ visit and any menu click but not change page.  chrome is fine

**Comment by schomery** [comment]
I see! I was testing on Chrome. Now I can regenerate the bug. Will update this when found a solution

**Comment by schomery** [comment]
Thanks for the report. Version 0.2.7 will fix this issue. Please wait for this version and if you still experience this issue after upgrade please reopen.

**Comment by DandyClubs** [comment]
thanks!!

pls support wildcard (*) or without subdomain rules
ex) *.cbox.ws or cbox.ws(subdomain www4~www7)

**Comment by schomery** [comment]
So the matching filter is very simple. Just add the `cbox.ws` to cover the domain and all its subdomains.

**Comment by DandyClubs** [comment]
i add cbox.ws 

http://prntscr.com/e8ylcz

but popup block

http://prntscr.com/e8ylcz

**Comment by schomery** [comment]
how can I reproduce this?

**Comment by DandyClubs** [comment]
visit http://alemdarleech.com/

name input dandyclubs

and login click

**Comment by schomery** [comment]
I think old entries are not being shown when you open this link. I tested with another link which had `www.`. Added the domain name only and popup was allowed.

**Comment by DandyClubs** [comment]
my case is not work.

my setting
http://prnt.sc/e8yu8m


http://prnt.sc/e8yu3r
