### ISSUE TITLE
Popunder defunct

### ISSUE THREAD

**Issue by flyingzebras** [schomery/popup-blocker#22]
I don't have a chance to block popunders with Popup Blocker (strict).

Visit [pornhub](http://pornhub.com/) and click on any video to trigger a popunder like this:

# pornhub.com visited
![1](https://cloud.githubusercontent.com/assets/11916082/22958279/a0ff7aee-f32e-11e6-9c95-5863c5e73fc6.png)

# A video is clicked on
![2](https://cloud.githubusercontent.com/assets/11916082/22958278/a0ff74ae-f32e-11e6-9dbd-6ab47baa59d2.png)

# 1 second after the video has been clicked on
![3](https://cloud.githubusercontent.com/assets/11916082/22958280/a0fff33e-f32e-11e6-8ede-b49bf0ae9b1c.png)

**Comment by schomery** [comment]
turn on `prevent page redirection` in the options page.

**Comment by flyingzebras** [comment]
@schomery Erm, I don't like that I have to change the settings for any popunder websites.

**Comment by flyingzebras** [comment]
@schomery That didn't help. Try it yourself.

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)
