### ISSUE TITLE
Request: full preview blocked url.

### ISSUE THREAD

**Issue by htomeload** [schomery/popup-blocker#23]
I just saw in some site which have very long url contain with parameter. Popup blocker work fine but I can't see full url of it. So, I can not recognize it which it is safe or not.

It may can done by simple HTML attribute like "title" which it can make tooltip when hover in element which contain this attribute. Or maybe just have one more button which will expand more space in  notification box to fit with blocked url.

It may need to stop counter when user is hover or click expand button, it will help user to have more time enough for recognizing url.

**Comment by schomery** [comment]
Thanks for the suggestion. We already had this `title` thing over the `p` element, but to have better coverage, it will be added to the main `div` element.
https://github.com/schomery/popup-blocker/blob/master/src/data/ui/ui.js#L144

> It may need to stop counter when user is hover or click expand button

done. you can check this on the dev version right now.
https://github.com/schomery/popup-blocker/archive/master.zip
