### ISSUE TITLE
Issue with popups registered on click capture

### ISSUE THREAD

**Issue by SlugFiller** [schomery/popup-blocker#27]
I'm visiting a site with  popup script that adds a listener for "click" on the "html" element on the capture phase. When the popup blocker stops the popup, the script seems to detect this, and doesn't de-register the listener. What's worse, because the listener is in the capture phase, the buttons to allow or deny the popup are unclickable, since they are part of the document (instead of being part of the frame).

I'm not sure what the solution could be. Moving the buttons to the frame, faking a successful popup, and/or giving an option to remove the offending event handler. But right now, sites that use this method are unnavigable.

Example offending script:
https://d3al52d8cojds7.cloudfront.net/?cdlad=622571

**Comment by JonasNo** [comment]
Example sites would be nice.

**Comment by narcolepticinsomniac** [comment]
Those look like Popads throwaway domains. As soon as they get flagged by adblockers, they're on to the next list of domains:

![popads](https://cloud.githubusercontent.com/assets/14100003/25244006/06413cc8-25cd-11e7-8682-0d3fbdba6050.jpg)

They're probably the biggest player in the game. They are also the most determined when it comes to circumventing adblockers and popup blockers, and will definitely attempt to sabotage functionality if their scripts detect blocking. 

They have zero standards when it comes to malware types of popups which hijack browser alerts and freeze your browser, demanding ransom and claiming to be Microsoft or the FBI, or whatever nonsense. Often times, the only way to unfreeze the browser is to kill the process in task manager.

PBs does block their popups, but OP is right that the listener isn't de-registering. That didn't used to be the case, so hopefully it's fixable. 

I use a combo of 3rd-party and inline-script blocking on sites that use Popads, because if their popups are blocked, they tend to sabotage sites so much that they're unusable. Disabling my adblocker to test sites is pretty horrifying, but here's an example site:
[Popads Example.txt](https://github.com/schomery/popup-blocker/files/944964/Popads.Example.txt)

**Comment by SlugFiller** [comment]
It took some effort, but I figured out how to recreate their trick with a simple page:
```
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Annoying popup</title>
		<script type="text/javascript">
			(function() {
				var okay_i_popped = false;
				function listener(e) {
					if (okay_i_popped) {
						e.currentTarget.removeEventListener("mousedown", listener, true);
						e.currentTarget.parentNode.removeChild(e.currentTarget);
						return;
					}
					e.preventDefault();
					e.stopPropagation();
					var win = null;
					try {
						win = window.open('about:blank', 'annoying');
					}
					catch(t) {
					}
					if (win && (typeof win === "object") && win.toString() === "[object Window]") {
						okay_i_popped = true;
						e.currentTarget.removeEventListener("mousedown", listener, true);
						e.currentTarget.parentNode.removeChild(e.currentTarget);
					}
				}
				var mylistenerdiv = null;
				function checkforlistener() {
					if (okay_i_popped) {
						return;
					}
					window.requestAnimationFrame(checkforlistener);
					if (!document.body) {
						return;
					}
					if (mylistenerdiv) {
						if (document.body.children[document.body.children.length-1] != mylistenerdiv) {
							if (mylistenerdiv && mylistenerdiv.parentNode) {
								try {
									mylistenerdiv.parentNode.removeChild(mylistenerdiv);
								}
								catch(t) {}
							}
							mylistenerdiv = null;
						}
					}
					if (!mylistenerdiv) {
						mylistenerdiv = document.createElement('div');
						mylistenerdiv.addEventListener("mousedown", listener, true);
						document.body.appendChild(mylistenerdiv);
					}
					mylistenerdiv.style.position = "fixed";
					mylistenerdiv.style.top = "0px";
					mylistenerdiv.style.left = "0px";
					mylistenerdiv.style.bottom = "0px";
					mylistenerdiv.style.right = "0px";
					mylistenerdiv.style.zIndex = 2147483647;
				}
				window.requestAnimationFrame(checkforlistener);
			})();
		</script>
	</head>
	<body>
		<a href="#test">You want to click me</a>
	</body>
</html>
```
This small page example will prevent dismissing the popup that will not open. If the blocker is disabled, it correctly displays the popup and deregisters.

The example page provided by @narcolepticinsomniac did manage to get a popup to actually open on occasion, but I'll leave that for separate research and post, if it becomes an issue.

P.S. While I copied the method used to block PBs's mouse input, the method I used to detect a failed popup is original, and may not be the same as the one used by popads.

**Comment by schomery** [comment]
@SlugFiller so basically when `window.open` is blocked, an object was replaced the actual window object that records some of the window's methods till now. In the last commit I am experimenting with passing an actual window object to the script but disabling some harmful functions like `window.write` or `window.open` [This might open new methods to pass the blocker, I am still not sure!]. This method is just harder to detect, that's it! For instance some simple checks like the one you've used in the sample html is passed. Please give it a try on an actual website and let me know if it works or not.

**Comment by SlugFiller** [comment]
As I've said, my concern is less with how the popup blocker is detected (It could even be as simple as placing a script in the popup window that uses window.opener), and more the fact that the overlapping div prevents access to the popup blocker's window.

Try clicking "allow" or "deny" in the example page I created, and see what happens. In my actual original case, I tried to press "background", in the hopes that opening the window as a tab would diffuse the popup script (Without creating a whole new window). But PBs's UI becomes inaccessible.

The issue is that PBs's UI is in-DOM. Compare to plugins like Session Manager that place their UI in the toolbar.

**Comment by schomery** [comment]
> ... more the fact that the overlapping div prevents access to the popup blocker's window.

Okay got it. It wasn't working in Chrome without adding a `background-color`; https://github.com/schomery/popup-blocker/blob/master/test/blocking-ui.html#L63

There are two new features that hopefully fix this issue:

1. It is now possible to completely disable the popup blocker and hence allow the script to open the popup!
2. There are two new items in the right click context menu to allow and deny the last request even if the UI is blocked.

**Comment by schomery** [comment]
> It is now possible to completely disable the popup blocker and hence allow the script to open the popup!

@narcolepticinsomniac this might conflict with https://github.com/schomery/popup-blocker/issues/5. Can you confirm it is not conflicting?

**Comment by schomery** [comment]
@narcolepticinsomniac about this `Popads Example.txt`. We have a situation here. To effectively block all sorts of window opening requests, we need to insert our script before page load and overwrite some of the native methods like `window.open` (this is a synchronous injection). Then if popup blocker is disabled for any reason, we will replace our methods with the native ones. This second action is asynchronous as it needs communication with the background script.

Now if a malicious script only checks popup blocker existence on the first load which is going to be after native methods are replaced by PB and before they are released again, it will assume the popup blocker is active even after native methods are released! This is exactly what happens in the sample link. That's the reason why even after [the new fix](https://github.com/schomery/popup-blocker/commit/f1736cc6f470a5db2d710ebd2b52d4d7a0cc9ffb) still you need to disable the extension to allow this script.

**Comment by narcolepticinsomniac** [comment]
> this might conflict with #5. Can you confirm it is not conflicting?

No conflict, with that script at least.

In regards to `Popads Example.txt`, a lot of the technical mumbo-jumbo is over my head. What I can say for sure is that "disabling the extension to allow this script" sounds like a pretty terrible solution. 

As I mentioned, Poper-Blocker seems to block a couple and deregister the listener. I guess that's only accomplished by either tricking it to thinking they've opened, or some other forced negation. They have some feature for "overlay blocking". I kinda figured that was a separate function from popup blocking, but perhaps they're related somehow. 

Btw, what's the verdict on https://github.com/schomery/popup-blocker/issues/12#issuecomment-295856672 ?

**Comment by narcolepticinsomniac** [comment]
I reinstalled a couple of the decent ones to check, and Poper-Blocker and Popper Stopper Pro both block the popups and deregister the listener on the example page. I double-checked without that overlay feature enabled and it doesn't make any difference. Probably just an extra CSS overlay remover, like the name implies.

**Comment by schomery** [comment]
> I reinstalled a couple of the decent ones to check, and Poper-Blocker and Popper Stopper Pro both block the popups and deregister the listener on the example page

None of these two seems to do blocking the way we do in this extension. I'll try to find a way to fix this, but I am not even sure it is doable!

**Comment by narcolepticinsomniac** [comment]
Weird thing is, it used to be the other way around. The others weren't deregistering, and PBs was. Like I said, Popads is the worst. On sites where they're used, I typically block 3rd-party and inline-scripts and then selectively allow necessary scripts for functionality. PBs is mostly a nice backup, especially when visiting new sites.

Sometimes if the listener isn't deregistered, you might not even notice, although I hide the iframe notifications, which would be really annoying. I have seen it cripple different functionality though, sometimes to the point where the site becomes unusable.

Hopefully there's a fix. Assuming there is, I'm sure you'll figure it out.

**Comment by schomery** [comment]
> the buttons to allow or deny the popup are unclickable

We now have a method to detect if there is an element overlapping with our notification box; https://github.com/schomery/popup-blocker/commit/5a85a1f842e6afe392bf541d2dd229e37cb28602 since I wasn't able to actually test this new feature, I'll keep the two last action buttons on the right-click context menu, but we should get rid of them if they are unnecessary. if anybody can confirm the new fix works, I'll remove them.
