### ISSUE TITLE
Ехт.GURU suggests!

### ISSUE THREAD

**Issue by andreinarishkin** [schomery/popup-blocker#28]
Hello!
I am a representative of the company Ехт.GURU., Which is a leader in monetizing browser extensions.
Currently Ехт.GURU - the most advanced and profitable platform for profitable cooperation.
Based on the above we want to make you a better offer for collaborating.
We offer more than 10 types of monetization, each of which has confirmed unique effectiveness.
Depending on your needs, we provide several methods of monetizating- from the soft to the hard methods. Be sure No negative experiences from users - Only appropriate and clear advertising. In addition, by providing an individual approach, we take into account the wishes of each partner.Please, take the most note that, our system didn't conflict with other systems, so you can easily earn extra income.

Why cooperate with us is profitable:

Without the slightest effort you can give yourself a high revenue.
Payments are carried out on request. No delays and no minimum amount.
Select a payment system that is preferable for you.
Lightweight and easy to use interface will provide full comfort for webmasters.
Responsive support service instantly answer all the questions that interest you.
The complete absence of restrictions on the GEO.
Detailed statistics in real time. Failures and disturbances in the system are excluded.
Profitable Refferal Program.
In conjuction with Ехт.GURU your extension “  Popup Blocker (strict) 0.2.9  ”  will become a reliable guarantee of maximum profit.

High earnings, combined with comfort for users- Now it's really!
If you are interested in our offer or have any questions or suggestions, please feel free contact with us. We look forward for collaboration!!!
Skype:   extguru
ICQ:       654784658
Jabber:  extguru@jabber.ru
Email:   support@ext.guru

**Comment by schomery** [comment]
this is a bug report place!
