### ISSUE TITLE
Official website opens on every upgrade

### ISSUE THREAD

**Issue by kirill9000** [schomery/popup-blocker#32]
Please remove these annoying pop-ups (so to speak) of addon's website on every upgrade and uninstall.
If I want to read news or send feedback I'll do it by myself.
Thank you.

**Comment by schomery** [comment]
There is an option in the options page to disable FAQs opening on upgrades.

**Comment by kirill9000** [comment]
I don't see any such option. Version 0.2.9.

Anyway, I think such option should be opt-in, not opt-out. You've built an excellent addon to help user combat annoying ads. Why spoil it by adding annoyances yourself?

**Comment by schomery** [comment]
Valid point. FAQs on update is now opt-in.

**Comment by kirill9000** [comment]
>FAQs on update is now opt-in.

Thanks! What about install and uninstall?

**Comment by kirill9000** [comment]
@schomery Hello? Have you decided not to remove install and uninstall popups?

**Comment by schomery** [comment]
Sorry I must have forgotten to reply. The first install FAQs page is a must have. Otherwise I am receiving too many emails asking about general things that are already mentioned in the FAQs page. The uninstall page is also very inspiring for the development. I am getting an idea why most of non-expert users are uninstalling this extension. This way I can fix issues or enhance the extension.

**Comment by kirill9000** [comment]
>FAQs page is a must have

Maybe you could place it inside extension itself and open locally?

>The uninstall page is also very inspiring for the development.

Same here. A local page with suggestion to email ideas for improvement would be nicer IMHO.

**Comment by schomery** [comment]
> Maybe you could place it inside extension itself and open locally?

That just makes things more complicated. I can now edit the FAQs page whenever there is a new feature or something useful to users. Besides, there is a discussion section that user can ask questions in the current FAQs page which is very helpful.

**Comment by kirill9000** [comment]
How about opening small local page with link to website? It would let user decide if he wishes to go there to view FAQ or send feedback.
