### ISSUE TITLE
0.3.0 breaks certain websites by showing a blank screen

### ISSUE THREAD

**Issue by mrdokenny** [schomery/popup-blocker#33]
Steps to reproduce:
On Firefox 54 on Windows 10.
Go to: https://discourse.mozilla-community.org/
You will see a blank screen but if you disable popup blocker, then the site works as normal.
Another site that are broken is the new Youtube layout UI.
Version 0.2.9 still works perfectly with the above websites.

**Comment by schomery** [comment]
That's right. 0.3.2 should have fixed this. Chrome version is released. Firefox is still on review.

Thanks for the report.

**Comment by mrdokenny** [comment]
Can confirm it's fixed now.

**Comment by tymes** [comment]
0.3.3 it's still here in chome:

when any domain is entered into Black-list options, a few websites appear blank after rendering is finishes (so after it seconds website blanks to white).

sample troubled websites: scene.ca and gizmodo.com, oh and lysol.ca airwick.ca (rb.com brands)


clicking on the icon to disable PBs (turning it grey from blue) doesn't seem to disable the extension and the extension must be disabled from chrome://extensions for the websites to finish rendering and appear.  The extension seems to always be active even when grey and interfere with websites.
