### ISSUE TITLE
Enable only on certain websites

### ISSUE THREAD

**Issue by rayman89** [schomery/popup-blocker#37]
Would it be possible to make the addon only do it's job when you are on a certain website. So for example on all the rest of the sites it will allow all the popups but on badsite.com it will be active and block popups?

**Comment by Keith94** [comment]
Add your host names to the black-list in the settings page.

**Comment by rayman89** [comment]
will that auto enable the addon on that pages if i disable it or how does that work? @Keith94

**Comment by Keith94** [comment]
Yes. Look under "descriptions" in the settings for how it works:

>Comma separated list of host names that popup blocker should only be active on them. This means popup block is disabled on ALL other domains

**Comment by rayman89** [comment]
yeah I tried that but the addon still works for all the sites and if I disable it, the addon does not auto enable itself on the blacklisted sites. @Keith94

**Comment by Keith94** [comment]
Hmm, did you remember to click on "save settings" afterwards?
I just blacklisted one domain `9tensu.com` and it only affects that one. Dev @schomery should know more about this.

**Comment by rayman89** [comment]
I tested blacklisting github and pressing save then reloading this page and the test page http://tools.add0n.com/popup-blocker.html and on the test page the popups keep getting blocked.

**Comment by rayman89** [comment]
I tested blacklisting github and pressing save then reloading this page and the test page http://tools.add0n.com/popup-blocker.html and on the test page the popups keep getting blocked. @Keith94

**Comment by Keith94** [comment]
I notice the same behavior, even after removing `add0n.com` from the whitelist. So it may be a bug.
For other domains (e.g. `thepiratebay.org`) it seems to work fine.

**Comment by schomery** [comment]
> I tested blacklisting github and pressing save then reloading this page and the test page http://tools.add0n.com/popup-blocker.html and on the test page the popups keep getting blocked

`tools.add0n.com` is an exception to allow users to test the popup blocker.

> I notice the same behavior, even after removing add0n.com from the whitelist.

For blacklist mode to work you need to refresh tabs. If it is not working as excepted (considering tools.add0n.com is an exception), please provide details.

**Comment by rayman89** [comment]
Seems to be working now. You can close this.,
