### ISSUE TITLE
No option checkbox on Firefox 55.0b5 (64-bit)

### ISSUE THREAD

**Issue by zmni** [schomery/popup-blocker#38]
![addon](https://user-images.githubusercontent.com/841523/27731890-2221c06a-5db9-11e7-841e-5c38d88f5ae2.jpg)

I try new install, clean install, reinstall, the checkbox still not showing. Can you look into this? Thanks.

**Comment by schomery** [comment]
This seems like have been fixed itself. Let me know if not.
