### ISSUE TITLE
Timeout for displaying each popup problem

### ISSUE THREAD

**Issue by happysurf** [schomery/popup-blocker#4]
In last 0.2.0 version if I change manually (input or clicking) the timeout under 10 (5 or 6) after saving the value back to 10.

**Comment by schomery** [comment]
10 is the minimum possible value; https://github.com/schomery/popup-blocker/blob/master/data/options/index.js#L33

Is there any reason why you need less?

**Comment by happysurf** [comment]
In my opinion 10 is too much as minimum value, in any case in the previous version less was permitted.

**Comment by schomery** [comment]
Okay then, will be fixed on the next release. Thanks for the report.
