### ISSUE TITLE
Not working on animeflv.net

### ISSUE THREAD

**Issue by rayman89** [schomery/popup-blocker#40]
When animeflv is blacklisted popups from that site still appear. The popups have a timer or something like that so after the first one appears it will take some time for an other to appear but they do by clicking anywhere on the page.

**Comment by schomery** [comment]
I am not sure how to get popups! Where do you click to get popups? Do you have an adblocker? what is your browser?

**Comment by rayman89** [comment]
Anywhere on the page you click you get a popup but it happens once every "x" amount of random time i think . I have ublock origin but disabling it still creates the popup the difference is that with it disabled it doens't close after a few seconds and it displays the advert. Im using firefox 55 beta x64 on windows 7.

Here is an example page https://animeflv.net/browse?q=dragon+ball

I created a thread on greasyfork like a year ago to see if it could be blocked and they helped me with a script but the site got updated

https://greasyfork.org/en/forum/discussion/10738/disable-clicking-anywhere-on-the-page-opens-a-new-tab-with-ads

**Comment by schomery** [comment]
Okay then this is certainly FF only issue. Can you confirm by installing the extension on Chrome?

I've already filled a bug and it is marked as `WONTFIX`; https://bugzilla.mozilla.org/show_bug.cgi?id=1342418. 

Since this is WebExtension bug in FF I am closing this

**Comment by rayman89** [comment]
I tested it on chrome and on firefox and I wasnt able to trigger it again in neither of those. I wish I had more sites to test it.

Either way would be possible for the addon to detect the script that did this to an about:blank pop:up/under once it already happened and block it (or notify the user of the specific script url so they can add it to an adblocker or something) so it wont happen more than once?

**Comment by schomery** [comment]
It is pretty hard to detect the responsible script. Even if it gets detected, it is very hard to filter it as the name and the domain of these scripts are constantly changing. The Chrome version should catch all these popup requests without any problem. You can reopen if you find an example that is not being blocked.
