### ISSUE TITLE
Another self sabotaging site

### ISSUE THREAD

**Issue by narcolepticinsomniac** [schomery/popup-blocker#41]
`https://www.iwatchonline.cr/`

Looks like another Popads site. They have the site inject it as an inline script. It never quits running and breaks functionality, like the search input.

**Comment by schomery** [comment]
Can you try the latest dev version. When the extension is disabled, you can open links. At least it is working for me.

**Comment by narcolepticinsomniac** [comment]
>When the extension is disabled, you can open links.

I have no idea what you mean by that. 

>When the extension is disabled...

I'm talking about how the extension works on a certain site, so how does disabling it factor in?

>...you can open links

Opening links wasn't the problem. The issue is that the popup script loops and never releases, and self sabotages functionality until the script has released, which it never does. The functionality broken is the header search input, as is often the case when the script doesn't release. Can't even get the cursor int the input, let alone type, or see suggestions.

**Comment by schomery** [comment]
Please reopen if it is not working as expected.

**Comment by narcolepticinsomniac** [comment]
>there is a new item in the right-click context menu over the toolbar button to allow shadow window creation

I think you're on the right track with this tactic. Tricking it into thinking it has worked will likely be the only way to release the loop. Unfortunately, it doesn't seem to work with adblock enabled, and it also doesn't work at all on similar sites, like:
[popups.txt](https://github.com/schomery/popup-blocker/files/1162544/popups.txt)

Even on the site in the OP, (with adblock disabled) the loop releases, but they're still sabotaging functionality. You can type in the search input, but suggestions don't work. They've really gotten good at ruining functionality if popups are blocked. Some sites you just have to give up on, but I'm still hoping you outsmart them.=)

If this feature becomes more refined, I would hope for something more automated, even if you'd need to blacklist manually. Also, in the right-click menu, you wrote "show" instead of "shadow".

**Comment by schomery** [comment]
The latest dev version has a new internal function that delivers click to the input elements if shadow window is active. Based on my tests it works even if you have adblocker in both sites.
