### ISSUE TITLE
after rendering websites disappear

### ISSUE THREAD

**Issue by tymes** [schomery/popup-blocker#43]
maybe return of #33 0.3.0 breaks certain websites by showing a blank screen

I get blank empty sites on scene.ca and gizmodo.com and several other websites. The websites starts appearing, and after a second when it should finish rendering it all goes blank.  Only when I go chrome://extensions and disable specifically "Popup Blocker (strict)" does the page display properly.  PB(s) doesn't even seem to do anything yet it seems to be what's causing the problem.  

Reproduce this in chrome by entering any domain (any.domain for instance) into Options, Black list.

so gizmodo.com (or affiliated websites like deadspin.com lifehacker.com), lysol.ca or airwick.ca (or other rb.com brands in canada like veet.ca), scene.ca...

Hmm, scene.ca was among the set of troubled sites but it's working now after I deleted and reinstalled the extension.  Hmm, or maybe not --  for that one website it's finicky and sometimes works and sometimes doesn't.  I can reproduce the problem with the other websites consistently.

Also even if I disable it? by clicking the icon and change it from blue to grey (what does that do?) nothing changes, I have to go to chrome://extensions and disable it there.

Oh, if I add the troubled website to the Black list, the website works?!  Erg, only when the extension is enabled via the icon (blue) -- which is counter intuitive!  so this problem with Black list seem to somewhat more profound and there must also be a problem with disabling this extension as it is still breaking things even when supposedly off (grey) and must be completely disabled via chrome://extensions.

**Comment by schomery** [comment]
Thanks for the report. It is now fixed on 0.3.4 via https://github.com/schomery/popup-blocker/commit/dcbc81ffe8c69f24fd193c7349e1b7d831361ebe

**Comment by tymes** [comment]
Yup, fixed.... 

but was the Option: Black List completely broken?   does clicking the icon and Blue<=>Grey work and completely disable the extension (minus the icon)?  The convolution of disparaging problems seemed more complex than one simple thing.

So now does having bogus domain like "nosuch.domain" in the "Black-list" all behave in as the same way as when the icon is "grey"?  aka the extension should be disabled for all websites and the only thing working should be the icon/menu.   I don't understand how it was still working or how that would be allowed to happen.


Meanwhile, in the future, the menu should be expanded to have a option to add the current domain to a list of "black-sources" that should be really strict (the current "Black list"?), an option to add the current page to a "black-targets" that should be blocked and closed and never visited (untrusted targets), and "white-targets" sites that are ok and we like... oh and and a "white-sources" where we want to allow popups.   This would be a new feature and would automate things a bit.


In the options you might also consider renaming 3: "Black-list (webpage)" as "Blacklist-Sources" and 2: "White-list (webpage)" as "Whitelist-Sources" and 1: "White-list (popup)" as "Whitelist-Destinations".   I think you've just added hyphens but my suggested names might be more apt descriptions.

**Comment by tymes** [comment]
you don't need to respond.  Thanks.
