### ISSUE TITLE
Problems with onedrive.live.com

### ISSUE THREAD

**Issue by caglarkoksal** [schomery/popup-blocker#48]
When I am trying to open a Word document from onedrive.live.com, pop-up blocker notifies me for a pop-up request, as shown below:

![capture](https://user-images.githubusercontent.com/10465183/29578429-2ded1f16-8767-11e7-899f-1ae094c00813.PNG)

However, clicking on allow opens a blank page. I've added live.com both to whitelist destinations and sources, but to no avail. Only after I disabled pop-up blocker then I could open word documents from onedrive.live.com

For comparison, pop-up requests made from gmail also trigger about:blank pop-up window, but unlike onedrive.live.com, these pop-ups would successfully open. This makes me think that the problem lies with onedrive.live.com, not with pop-up blocker, but if we can find a working solution to this, that'd be great! Cheers. 

If relevant, I am using firefox 55.0.2 on win10.

**Comment by schomery** [comment]
Thanks for the report. It will get fixed in the next release. For now, you can temporarily disable the extension from toolbar button and when the page opens, reenable it.
