### ISSUE TITLE
Pop-up blocker interferes with TamperMonkey userscripts

### ISSUE THREAD

**Issue by narcolepticinsomniac** [schomery/popup-blocker#5]
I use a modified version of the same script on lots of different sites to remove content based on text content. They suddenly stopped working when I started using this popup-blocker full time. I know you need to prevent a lot of defaults, but I've never had a popup-blocker affect any userscripts. I always figured userscripts were always allowed to have priority. The example I have is NSFW, but I tried to pick the tamest content for an example script. 

In TamperMonkey install:
<pre>// ==UserScript==//
// @name        Test
// @version     1.0
// @include     http://sexix.net/*
// @run-at      document-start
// @require     https://greasyfork.org/scripts/12228/code/setMutationHandler.js
// ==/UserScript==

// process the already loaded portion of the page
process(document.querySelectorAll(
    'a'
));

// process the stuff loaded from now on
setMutationHandler(
    document,
    'a',
    process
);

function process(nodes) {
    for (var i=0, n; (n=nodes[i++]); ) {
        if (n.textContent.match(/lesbian/i)) {
            (n.closest('.item') || n.parentNode).remove();
        }
    }
}</pre>
and then follow this link http://sexix.net/?s=lesb

Without your extension enabled, the script functions as expected. With your extension enabled, it fails. 

On a sidenote, I also had to disable it to use the "insert code" markdown function here. It's not like I don't expect it to have some unintended side-effects (that's what whitelists are for), but there has to be a way to ignore TamperMonkey scripts.

**Comment by schomery** [comment]
Thanks please give the latest dev a try and let me know if the issue is fixed or not;

1. Open chrome://extensions/ and disable your popup blocker
2. Check "Developer mode" checkbox
3. Download [the latest dev version](https://github.com/schomery/popup-blocker/archive/master.zip) here and extract it in a folder
3. Point "Load unpacked extension" to the root of the extracted folder
4. Refresh the page

P.S to make the popup blocker compatible with TamperMonkey I had to allow some objects to be writable. So this might have affect on blocking power of the extension. So let me know if you happen to see a popup that can pass the popup blocker.

**Comment by narcolepticinsomniac** [comment]
Yeah, the userscript works now, but popup-blocking performance is definitely affected. A lot of examples will also be NSFW because they're some of the worst sites, and I accidentally end up on different ones all the time. Strange how that happens.

Blocked in 2.1, not so much in 2.2:
http://sexu.com/
http://hdreporn.com/
https://www.eporner.com/

On a sidenote, the second player (datoporn iframe, black play button) here:
http://www.xmoviesforyou.com/2016/11/girlsway-celeste-star-aj-applegate-kimmy-granger-lesbian-coming-stories-part-two.html

is flaky with either. Sometimes it catches them, sometimes it doesn't. A few page loads should repro misses.

You can't take the "strict" out apparently. I really figured you'd make exceptions for initiators with:
chrome-extension:// prefixes or something along those lines, but that's purely speculation on my part.  If I knew how to do what you're doing, I'd have done it already.

**Comment by schomery** [comment]
I think I got this fixed. Please give the latest dev a try.

P.S: I removed the links to prevent having references to these sites.

**Comment by narcolepticinsomniac** [comment]
It's a lot better, but only if "Do not block popup requests from same origin" is not enabled. In theory, this is a useful option, but whatever deobfuscation you're doing to links is creating an extra "same page you're on" popup which is only blocked if requests from the same origin are blocked. 

Still, it's vastly improved.

I will likely have to link some smutty sites as examples, since they're some of the worst offenders. Of course you're welcome to sanitize after, or if there's a better way you'd like me to go about it, let me know.

As I mentioned previously, blocking is unreliable for the second player (datoporn iframe, black play button) here:
http://www.xmoviesforyou.com/2016/11/girlsway-celeste-star-aj-applegate-kimmy-granger-lesbian-coming-stories-part-two.html

Sometimes it catches them, sometimes it doesn't. A few page loads should repro misses. It seems likely that they are using the same method, so I wonder if iframe injection is an issue.

**Comment by schomery** [comment]
> I will likely have to link some smutty sites as examples

No problem. But please try to to attach links in a text file instead of directly posting them. I think this way we can prevent back linking to these websites

> As I mentioned previously, blocking is unreliable for the second player (datoporn iframe, black play button)

In the new dev version, I added protection for a few more blocking methods, hopefully this is fixed. Please give the latest dev a try.

**Comment by narcolepticinsomniac** [comment]
It's catching popups very well. The ones it's missing aren't technically popups, they're same page redirects. The previously mentioned iframe player has lots of blocked popups, but every so often they inject a redirect instead. Reproducing is unreliable, perhaps it's every certain number of clicks?

Regardless, it seems like the same method used consistently here:
http://thevideo.me/q9mhldtdc7z1

Once you get to the video page, clicking anywhere causes a same page redirect. It's worth noting that none of the blockers I've tested catch these. The above site is particularly evil because no matter how many times you're redirected and go back, the click-jacker is never removed. It's a never-ending redirect loop. 

Maybe these are too difficult to account for, but your skills have been impressive so far, so maybe not.

**Comment by schomery** [comment]
@narcolepticinsomniac please share few more links that use this redirection technique. I am trying to find out if all these scripts use the same technique or not. Basically it seems the JS code checks some properties of the newly generate window and if a property is missed, then redirection command is issued. If I have more examples I might be able to find a solution for this.

**Comment by narcolepticinsomniac** [comment]
Sure. I've been using yours full time, and it's very good at blocking popups. I'm sure the same page redirects are a different beast, and most popup blockers don't account for them. They might be even more annoying, which is probably why not a whole lot of sites use them. I'm sure people draw the line and just quit visiting sites that use them altogether. 

Anyway, I've got a couple other examples.
This one seems like a clone of "thevideo.me":
http://vidup.me/tdfxt6kp45i3

The other is NSFW, so I'll put it in a text file per your request:

**Comment by narcolepticinsomniac** [comment]
I told you before that your extension was screwing with markdown functions here on Github. It was just preventing me from attaching a file as well. I tried whitelisting, and also clicking the icon to disable, but the only way it worked was by disabling the extension.

For the most part, your whitelist function has worked well. I think it may be the extra layer of security/encryption Github utilizes on some pages (like this one). I know I use a "favicon changer" extension which works well, but not at all on "secure" Github pages. Don't know if there's any way around that, but I figured I'd let you know.

**Comment by schomery** [comment]
> I told you before that your extension was screwing with markdown functions here on Github. It was just preventing me from attaching a file as well.

I am not experiencing this. This might be a conflict with another extension of yours. Can you confirm this on a clean profile with just Popup Blocker installed?

**Comment by schomery** [comment]
> This one seems like a clone of "thevideo.me":

To get a redirect I need to refresh the page several times that makes it hard to catch the responsible script. I wish we could have another example that occurs on every click. btw, what adblocker are you using while visiting these pages.

**Comment by narcolepticinsomniac** [comment]
Confirmed. Brand new profile, only extension loaded. Couldn't "select" or drag & drop this text file, even with it "disabled" by clicking the icon. It had to be disabled on the extensions page for it to work. Here's another NSFW example of a same page redirect. It's only with a clean cache when clicking on the player. I use Ublock with some pretty hefty filter subscriptions and custom rules. I also keep a huge hosts file for blocking ads/tracking at the OS level. I frequent some pretty shady sites, and some of them aren't even functional without the proper mechanisms in place.

[popup-example2.txt](https://github.com/schomery/popup-blocker/files/635777/popup-example2.txt)

**Comment by narcolepticinsomniac** [comment]
Hey, I don't pay much attention to extension error logs unless they turn red, which PBU has recently. The warning is: 

Uncaught TypeError: Cannot read property 'addListener' of undefined

pointing to this line:

31) chrome.runtime.onMessage.addListener((request) => {

**Comment by schomery** [comment]
How can I regenerate this? Id this happening on all pages?

**Comment by narcolepticinsomniac** [comment]
Not sure that you could. I figured copying the highlighted line might be insightful. I should've made note of the current pages. My bad. Apart from there being any obvious syntax errors, I wouldn't worry too much about it. I have quite a few unpacked extensions, and most register errors occasionally. It's not great when they're red, but I haven't seen it since. If it happens again, I'll try to be more helpful with steps to repro.

**Comment by schomery** [comment]
> chrome.runtime.onMessage.addListener

This means the extension got disconnected from its context. Like when a document is reset with `document.open()` or something similar. Although the extension can handle message passing even if `chrome.runtime` is not present, though it is better to prevent the error generation. Let me know if you can find a link that is causing this issue.

btw, `popup-example2.txt` is not working anymore. If possible please update the link inside the text file.

Also I am still not able to regenerate the GitHub issue. On a clean profile file selection works just fine for me. Can you see if an error is generated once the "selecting them" is clicked?

**Comment by narcolepticinsomniac** [comment]
popup-example2.txt isn't much of an example for the time-being, the site has been down for a couple days. I made a screen record of the Github issue. Btw, as I've stated before, to block as many popups as possible, you're gonna wind up with some unintended side-effects. I really hope you don't sacrifice blocking capability to fix things. All I'd really like to see is both the whitelist and temporarily disabling it by clicking the icon work to allow whatever function is getting blocked. They don't seem to be working here for this particular bug.
[Pop-Git.zip](https://github.com/schomery/popup-blocker/files/658733/Pop-Git.zip)

**Comment by schomery** [comment]
Thanks, just one more thing. Please open the dev tools (right click anywhere on the page -> select inspect -> switch tab to console) and try it one more time to see if you get a new error in the console while adding a new file.

**Comment by narcolepticinsomniac** [comment]
I'm familiar with checking the console. Unfortunately, no new errors are recorded. I know you have a Mac, which I guess has no issue. Have you tried it on Windows?

**Comment by schomery** [comment]
How about the "network" tab? according to the screenshot the file gets uploaded, but not being attached to the box. You might get 404 error in the network tab.

Okay, I'll see if I can generate this on Windows too.

**Comment by narcolepticinsomniac** [comment]
Nope. Nothing new added or blocked in Network tab when it fails.

**Comment by schomery** [comment]
Still not able to reproduce this even on windows;
[Untitled.mov.zip](https://github.com/schomery/popup-blocker/files/658791/Untitled.mov.zip)

**Comment by narcolepticinsomniac** [comment]
Can't watch quicktime in mpc-hc, but I believe you. I have no idea. I tested again in Chrome on Win 8.1. I typically use Chromium, which is essentially the same as far as important internals. It's the only extension, and I get the same results as the video. It won't work till it's fully disabled.

Hey, you can't fix what you can't see. Ironically, this is the only place I've come across where it happens. If I need to disable it for attachments on Github, it's not the end of the world. It works well enough elsewhere that it's worth it.

**Comment by narcolepticinsomniac** [comment]
Another odd bug. I mentioned before that I use a userstyle to hide the notifications, so I don't always notice, but there are quite a few weird false positives. Some when just hovering links, like on http://9gag.com/. Just hover any of the title links.

**Comment by schomery** [comment]
I am not able to reproduce this either! If this is happening to other users I really need to fix this one!

These two issues might be only on Chromium. Let me know what is your Chromium version and I'll try to install the same version

**Comment by narcolepticinsomniac** [comment]
My bad, this one I didn't test in a clean profile. It's a conflict with another extension I sideload that's pretty buggy. I've been working on trying to fix it, but jQuery (or javascript in general) is not my strong-suit. If you're curious:
[YouHover.zip](https://github.com/schomery/popup-blocker/files/659284/YouHover.zip)

**Comment by schomery** [comment]
There is absolutely no need for jQuery for such a simple add-on; I created a simple one with pure Vanilla JavaScript; https://github.com/schomery/youtube-hover

**Comment by narcolepticinsomniac** [comment]
Man, if you can get that one working, you'll be moving up my list of internet heroes. I'm sure you've got it working on your end, but as frequently seems to be the case, I'm getting different results. As the only loaded extension in Google Chrome (for parity), I'm getting the div and an empty iframe with a loading gif.

The other one was hastily written if you read the description. The code is buggy as hell, but I had gotten a little help to at least fix the positioning so it was always vertically centered and switched left or right opposite the cursor position. Positioning may be better fixed than absolute, but I hadn't gotten around to that. I like how you handled the focus from what I can tell without the video. Hotkey toggles would also be overkill if focus is handled correctly.

Good testing: https://www.reddit.com/domain/youtube.com/

**Comment by schomery** [comment]
> As the only loaded extension in Google Chrome (for parity), I'm getting the div and an empty iframe with a loading gif.

Can you get it one more time from https://github.com/schomery/youtube-hover, I was commenting some code for debugging. The latest dev version is working fine on reddit.

**Comment by narcolepticinsomniac** [comment]
Yup! Vids are loading. Could be a bit bigger and the positioning like I mentioned if you're up for it, but I'm sure it's already a far better base to work with, so thank you. The other thing I was gonna attempt to work out was a very slight delay to negate incidental hovers.

**Comment by schomery** [comment]
> Positioning may be better fixed than absolute, but I hadn't gotten around to that

This is not really useful when there is a scrollbar. Though we can have it in the options page if you think this positioning could be useful.

> Could be a bit bigger

Adjust it in the options page. There is a delay in the options page as well.
If you believe we need more options, just open bug reports here https://github.com/schomery/youtube-hover/issues

**Comment by narcolepticinsomniac** [comment]
I have to go to work for a bit, but I am very much looking forward to playing around with this when I get back. It's a great little extension, but it needed a total rewrite that I couldn't have pulled off. Thanks for coming through with it, I really appreciate it!

**Comment by narcolepticinsomniac** [comment]
Hey, good news. I just checked in here and noticed you updated the master. I updated and now Github is bug-free. I can select files correctly and the markdown functions all work now. Figured I'd let you know.

**Comment by schomery** [comment]
Perfect! I am still not sure why this commit has fixed the issue, but anyhow it is a good news. 

> I just checked in here and noticed you updated the master

On you default chrome profile, use the WebStore version. This way you will get updates automatically.
