### ISSUE TITLE
Breaks sites like YouTube if paused

### ISSUE THREAD

**Issue by turbolocust** [schomery/popup-blocker#53]
Websites like YouTube or [https://www.webcomponents.org/](url) are broken if the popup blocking functionality is disabled (toolbar icon grayed out).

**Comment by schomery** [comment]
Thanks for the report!

**Comment by Myer** [comment]
When do you plan to push a new update? This is a really severe regression breaking such popular pages like YouTube.

It's already getting you bad reviews: https://addons.mozilla.org/de/firefox/addon/popup-blocker/reviews/

**Comment by schomery** [comment]
I've already submitted a new version and it is under review. Note that if PP is disabled, YouTube is not loading or if you are using the blacklist mode. So not so many are affected.
