### ISSUE TITLE
Unable to choose option from dropdown menu

### ISSUE THREAD

**Issue by caglarkoksal** [schomery/popup-blocker#56]
Firefox 55.0.3 on win10 with popup blocker 0.3.7. Tested on Chromium and had the same problem.

On this website ([https://fonts.google.com/?category=Serif,Sans+Serif,Display](https://fonts.google.com/?category=Serif,Sans+Serif,Display)), I am unable to choose Hebrew (or any other language) from `All Languages` dropdown menu on the right side panel when popup blocker enabled, which freezes the page if language option is chosen. Disabling the add-on circumvents the problem.

**Comment by schomery** [comment]
Thanks for the report. I am not able to reproduce this on the dev channel. Please reopen after 0.4.0 release if you are still experiencing this.
