### ISSUE TITLE
Breaks battlefield.com

### ISSUE THREAD

**Issue by muotila** [schomery/popup-blocker#58]
[Battlefield.com](https://www.battlefield.com/) fails to load properly when the add-on is enabled in the add-ons menu. Enabling it gives two new errors in console:
- TypeError: Argument 1 of Node.appendChild does not implement interface Node. (webcomponents.min.js:13:9114)
- Error: Assertion failed (webcomponents.min.js:11:1561)

 Tested with Firefox 55.0.3.

![battlefield](https://user-images.githubusercontent.com/32031255/30519327-5891e672-9b9c-11e7-821a-ff65ec985a78.png)

**Comment by schomery** [comment]
Thanks for the report. I'll investigate. It is not an easy one :)
