### ISSUE TITLE
[Bug] serials.ws

### ISSUE THREAD

**Issue by adreporter** [schomery/popup-blocker#59]
https://www.serials.ws/
After clicking on a serial, you'll see this box
<img width="261" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/30659334-c10c6f4e-9e3d-11e7-9a8e-24a648713f71.PNG">
I clicked on "trust" so I have this website in the <img width="114" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/30659590-8971072e-9e3e-11e7-865c-3ca2eb76f532.PNG">
The problem is that after clicking on "trust", the popup isn't showing. You have to click ALWAYS on "allow" to see the popup, even if the website is in the <img width="114" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/30659590-8971072e-9e3e-11e7-865c-3ca2eb76f532.PNG">
I'm using the latest version of Google Chrome [61.0.3163.91 (64-bit)]
Could you please fix this little bug?

**Comment by schomery** [comment]
Thanks for the report. It will get fixed in the 0.4.0 release.
