### ISSUE TITLE
Reload page after "Trust", "allow", and "redirect"

### ISSUE THREAD

**Issue by davidhedlund** [schomery/popup-blocker#62]
![screenshot from 2017-11-04 07 28 49](https://user-images.githubusercontent.com/6416073/32403029-d351f950-c131-11e7-93a1-7d55d6026527.png)

Currently I have to reload the page after I click on Trust for example, Popup Blocker (strict) should do this automatically.

**Comment by schomery** [comment]
This should get fixed in v0.4.0 release without the need to refresh the page. If not please reopen. Also please add a website link to check the issue.

**Comment by davidhedlund** [comment]
Thanks!

**Comment by davidhedlund** [comment]
Thanks!
