### ISSUE TITLE
missing icon on ff44

### ISSUE THREAD

**Issue by xevidencex** [schomery/popup-blocker#63]
Hi,

ff44 allows me to use all addons without severe compatibility issues, that's hwy i'll never update
to the latest ff to break 10 or more addons functionalities.

It would be nice to send me an up to date version that allows me to have the functional icon 
on firefox toolbar, using v44.

**Comment by xevidencex** [comment]
i don't think that even a greasemonkey script could add icons to the ff toolbar anyways, so i'm here for nothing anyways.

**Comment by schomery** [comment]
Sorry but the min version of Firefox for this add-on to work properly is FF52.0
