### ISSUE TITLE
Add a blacklist feature

### ISSUE THREAD

**Issue by Keith94** [schomery/popup-blocker#7]
There's only a few websites I visit that have popups in the form of advertisements that I wish to block, so a blacklist feature to block only certain ones would come in handy. I would rather not have to allow popups on every unaffected website. Can it be added?

**Comment by schomery** [comment]
Well, the problem is advertisement popups do many tricks to get their popup pass the browser popup blocker. For instance they try to open a blank page and then redirect it to the destination (this one cannot be blocked by blacklist filtering). If in your case you are not dealing with these sort of popups, simply define a few new rules for your adblocker add-on and it should block all the URLs just fine; https://adblockplus.org/forum/viewtopic.php?t=10348

**Comment by Keith94** [comment]
You're right, I've encountered these types of popups (redirecting from blank pages) on thepiratebay.org, I guess for these popup ads it's necessary to use your add-on? I've tried using uBlock Origins' dynamic filtering rules but I couldn't get it to block those.

**Comment by schomery** [comment]
It is really hard to block these sort of popups. That's the reason why we block all popups! If this extension blocks too much either wait for the next release that has two enhancements:
![screen shot 2017-01-09 at 12 15 25](https://cloud.githubusercontent.com/assets/11704051/21760985/55bd7878-d665-11e6-9ef7-a9cb045d34de.png)

1. It remembers your last action and automatically performs it
2. The "trust" button is added, so you can simply whitelist your domains.

or disable it by default though the toolbar button and turn it on only when you are on malicious sites.

**Comment by Keith94** [comment]
These features seem useful. It remembers your last action through browser cookies, correct? What if a user clears their cookies often, is there a better way to store that information?

**Comment by schomery** [comment]
Yes it is browser cookie, but not those that you can clear easily. To confirm install the dev version and give it a try https://github.com/schomery/popup-blocker/issues/8#issuecomment-271232524

**Comment by Keith94** [comment]
I loaded the dev version in Firefox, the cookies can be cleared the same as all the others. I don't know if that poses a problem, but it works well.

**Comment by schomery** [comment]
That's weird! these cookies are supposed to be stored privately. This is the case for Chrome. How did you clear the cookies? I havent yet tried it on Firefox.

btw, I added a new option in the options page to change the mode to blacklist mode. In this mode, the extension is only active on certain domains.

**Comment by schomery** [comment]
Okay I see. It is still better to have them on the document.cookie to have periodic clean up. This is not very important feature.

If I store them in the storage area, this might get huge after a while.

**Comment by Keith94** [comment]
That's great! Thanks for adding the blacklist. ^^

I can confirm it's working. Please publish a new version when you can.

**Comment by dspjm** [comment]
@Keith94 How did you enable the blacklist feature? I add a '*' in the white list source and destination fields, but it doesn't work.

**Comment by dspjm** [comment]
All right, I found the solution here:
https://github.com/schomery/popup-blocker/issues/37
