### ISSUE TITLE
[NSFW] Popup Blocker (strict) doesn't work on two websites

### ISSUE THREAD

**Issue by adreporter** [schomery/popup-blocker#71]
Hi,
unfortunately Popup Blocker (strict) doesn't block redirection on these 2 sites:
`http://drakulastream.tv/` and `https://www.nudevista.com/`
On the first site, it happens after clicking on the text "Select sport".
<img width="107" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/36063862-b4ae6a3a-0e82-11e8-894c-41b4932c4132.PNG">
On the second site, it happens after clicking on the text "English".
<img width="322" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/36199955-6f2d5150-117b-11e8-9ca5-5d8d16ec0f90.PNG">
I'm using the latest 64-bit version of Google Chrome.
Could you please fix it?

**Comment by schomery** [comment]
Can you try the latest developer version? https://github.com/schomery/popup-blocker
Make sure the release version need to be disabled, or you can try on a clean profile.

I am not able to reproduce this anymore.
