### ISSUE TITLE
Breaks VirusTotal file upload

### ISSUE THREAD

**Issue by FatOrangutan** [schomery/popup-blocker#76]
Reproducible in both Firefox and Chrome.

STR:
1. Visit `https://www.virustotal.com/#/home/upload`.
2. Click `Choose file`. Pick up some small file.
3. The `Choose file` button changes to `Calculating hash` button and upon completion, you are taken to the result page.
4. Now install Popup Blocker. Reload `https://www.virustotal.com/#/home/upload`. Pick some file using `Choose file`. Nothing happens - Popup Blocker doesn't say it blocked anything and the virustotal doesn't calculate hash or navigate to the results page.
5. Now disable Popup Blocker by clicking its toolbar icon. Virustotal works as expected.

**Comment by smed79** [comment]
I can reproduce the issue.

**Comment by schomery** [comment]
This will get fixed on the major 0.5.0 release. Thanks for the report. Please reopen if not.
