### ISSUE TITLE
Button text is light grey on white background [Firefox]

### ISSUE THREAD

**Issue by pizzadude** [schomery/popup-blocker#79]
I don't know if this is because of my userChrome.css, but the button text is light grey on white background, which means I have to look real close to read it. I'm using https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars as my userChrome.css. I am testing this on Firefox Nightly on Linux. It happens with stable Firefox also. I suspect this is because the font color for the button text isn't declared, but I'm not sure as I haven't looked at the source code yet. If it would be possible to fix this or make colors configurable that would be nice. Here's a screenshot so you know what I mean.

![light](https://user-images.githubusercontent.com/1454420/44098048-b00b3dd6-9fce-11e8-98ac-f2d1850d1896.png)

**Comment by schomery** [comment]
It should be fixed on the latest commit. Please reopen if you still have the issue after 0.5.0 release.
