### ISSUE TITLE
Remember decisions

### ISSUE THREAD

**Issue by rayman89** [schomery/popup-blocker#8]
It would be nice if the addon could remember if you deny or allowed it and did that every time ypu visit that page and the same popup/popunder comes up with the ability to see  the list of those decisions and change them if you somehow fucked up and wanted to block instead of allow or vice versa.

**Comment by schomery** [comment]
Good one. We will have it on the next production version. For now please give it a try and let me know if it works as expected or not.

To try
1. Open "chrome://extensions/" and turn the developer mode on;
2. Disable the stored popup blocker
3. Download https://github.com/schomery/popup-blocker/archive/master.zip and unzip it somewhere
4. Point the "Load unpacked extension" to the `/src` directory of the extracted active.

**Comment by schomery** [comment]
Note the you can adjust the countdown from the options page.

**Comment by rayman89** [comment]
I'm on firefox x64
