### ISSUE TITLE
[PB 0.5.0.2 - Chromium 68] Unable to load FB apps

### ISSUE THREAD

**Issue by smed79** [schomery/popup-blocker#82]
For testing purpose, I have download and load the unpacked [Popup Blocker 0.5.0.2](https://github.com/schomery/popup-blocker/files/2299184/pp.zip) to Chromium 68.

By chance, when trying to check an [\_issue\_](https://forums.lanik.us/viewtopic.php?f=64&t=41437) not related to PB, i have noticed that the FB game (iframe) does not load with PB enabled (e.g. `https://apps.facebook.com/criminalcase`).

Screenshots
- https://i.imgur.com/A8oVU0j.png
- https://i.imgur.com/sq25Uip.png
- https://i.imgur.com/fasSHLB.png

**Comment by schomery** [comment]
Thanks for the report. It should be fixed on 0.5.0.3 release.
