### ISSUE TITLE
Pop-in notification opens for iframes

### ISSUE THREAD

**Issue by smed79** [schomery/popup-blocker#86]
Probably related to https://github.com/schomery/popup-blocker/issues/82

example url : `https://www.vipbox.live/cracovia-vs-plock-2-live`

issue : Pop-in notification opens for iframes

Ss: 

- https://i.imgur.com/86PFQcM.png
- https://i.imgur.com/wR1rFMK.png
- https://i.imgur.com/Kv8W7aH.png

**Comment by smed79** [comment]
Another annoying behavior ...


**Description**

The sidebar search result on `wikimapia.org` open in new tab.

**How to reproduce**

Go to http://wikimapia.org/ then do a search for a city (e.g. London)

**Ss** 

* https://i.imgur.com/MSvciPo.png

**Comment by raszpl** [comment]
tested your vipbox link just now and blocking doesnt work at all inside the iframe, clicking anything inside iframe generates additional tabs
