### ISSUE TITLE
How to completely disable in-page-notifications issued by this extension

### ISSUE THREAD

**Issue by rayman89** [schomery/popup-blocker#9]
Could you add the ability to disable the popup saying allow/deny (maybe set seconds to 0) so we can have a block all unless whitelisted alternative way to use this add-on?

**Comment by schomery** [comment]
I think this is somehow dangerous action. If you have stylish add-on, try https://github.com/schomery/popup-blocker/issues/3#issuecomment-262404186

**Comment by rayman89** [comment]
Thanks. Do you know how to change it to affect firefox though. Seems to be a chrome only thing  iframe[src="chrome-extension://aefkmifgmaafnojlojpnekbpbmjiiogg/data/ui/ui.html"]{display:none!important;}

**Comment by narcolepticinsomniac** [comment]
Assuming you're using an extension like Stylish which requires `@-moz-doc`:

```
@-moz-document regexp("https?://.*") {
    iframe[src="moz-extension://44fa15d3-dc50-47c6-ba13-25dc2b8710d7/data/ui/ui.html"] {
        display: none!important;
    }
}
```

I would think the iframe source is consistent across all installs, but I'm not positive.

I also agree that the option to disable them completely should be available. The options in the notifications are very useful to some, I'm sure, but if you frequent as many sleazy sites as I do, the constant notifications when I want to block 99.9% of them gets old pretty quick.

**Comment by rayman89** [comment]
It worked but I had to change

`moz-extension://9c5cab37-52ac-4c8e-ada9-f59b67480458/data/ui/ui.html`
to
`moz-extension://44fa15d3-dc50-47c6-ba13-25dc2b8710d7/data/ui/ui.html`

Thanks
