### ISSUE TITLE
Extension prevents some sites from loading

### ISSUE THREAD

**Issue by PoorLissa** [schomery/popup-blocker#92]
https://lenta.ru/
This site displays its content for a short time and then all the page goes gray. Whitelisting (I tried all possible variants) does not help. The site only loads properly if the extension is completely turned off in browser's options. The browser is Opera.

**Comment by arlavit** [comment]
Same here on Firefox. You won't see the site while the addon is enabled. Clicking the addon button doesn't change anything.

**Comment by raszpl** [comment]
works fine for me (vivaldi), but that might be due to website js crashing with `TypeError: Cannot read property 'open' of undefined`

**Comment by schomery** [comment]
I am not able to reproduce this. Please reopen if you can.

**Comment by PoorLissa** [comment]
Can't reproduce it either. Something's changed about the site, probably.
