### ISSUE TITLE
what is https://www.facebook.com/tr/ ?

### ISSUE THREAD

**Issue by HackerGaucho** [schomery/popup-blocker#97]
![](http://i.imgur.com/FFsaXFh.png)

What is this warning that appears when no popup is activated? I have seen it when I visit pages like [TikTok.com](https://www.tiktok.com/@mileycyrus) for example.

**Comment by schomery** [comment]
This is an iframe by Facebook that is injected into some webpages to add support for commenting. The extension detects it as a popup. If you still see this popup please reopen with steps on how to generate it. Also, state your browser version.
